# Generated by Django 5.1.6 on 2025-02-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('compositor', models.CharField(max_length=255, verbose_name='Compositor')),
                ('arreglista', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arreglista')),
                ('genero', models.CharField(max_length=100, verbose_name='Género')),
                ('instrumentos', models.CharField(max_length=255, verbose_name='Instrumentos')),
                ('dificultad', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50, verbose_name='Dificultad')),
                ('archivo', models.FileField(upload_to='partituras/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('visibilidad', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=50, verbose_name='Visibilidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Partitura',
                'verbose_name_plural': 'Partituras',
            },
        ),
    ]
